version: '3.8'
services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_AUTH0_DOMAIN=dev-2cf59a31.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=rrwygXFgF8LgSGhV4ufVQprovN3iITpD
      - REACT_APP_AUTH0_AUDIENCE=https://reservationizr.com
      - REACT_APP_AUTH0_REDIRECT_URI=http://localhost:3000/reservationizr
    networks:
      - app-network

  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI==mongodb://mongodb:27017/mongo
    networks:
      - app-network

networks:
  app-network:
    external: true
