version: '3.8'
services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3002:3000'
    depends_on:
      - db
    environment:
      # - 
      -  REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      -  REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
      -  REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
      -  REACT_APP_API_URL=${REACT_APP_API_URL}
      -  REACT_APP_AUTH0_REDIRECT_URI=${REACT_APP_AUTH0_REDIRECT_URI}

  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5002:5000'
    depends_on:
      - db
    environment:
      - MONGODB_URI=${MONGODB_URI}
  db:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'
