version: '3.8'
services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3002:3000'
    environment:
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_AUTH0_REDIRECT_URI=${REACT_APP_AUTH0_REDIRECT_URI}
    networks:
      - app-network

  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5002:5000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - app-network

networks:
  app-network:
    external: true
