version: '3.8'
services:
  client:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - REACT_APP_API_URL=https://warricksmith.com/reservationizrapi
      - REACT_APP_AUTH0_DOMAIN=dev-2cf59a31.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=rrwygXFgF8LgSGhV4ufVQprovN3iITpD
      - REACT_APP_AUTH0_AUDIENCE=https://reservationizr.com
      - REACT_APP_AUTH0_REDIRECT_URI=https://warricksmith.com/reservationizr/

  server:
    build: ./server
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/mongo
  db:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'
  nginx:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
