version: '3.8'
services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_AUTH0_DOMAIN=dev-2cf59a31.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=rrwygXFgF8LgSGhV4ufVQprovN3iITpD
      - REACT_APP_AUTH0_AUDIENCE=https://reservationizr.com
      - REACT_APP_AUTH0_REDIRECT_URI=http://localhost:3000/reservationizr

  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/mongo
  db:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'