version: '3.8'
services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3002:3000'
    depends_on:
      - db
    environment:
      # - REACT_APP_API_URL=https://warricksmith.com/reservationizrapi
      - REACT_APP_API_URL=https://localhost:5002/reservationizrapi
      - REACT_APP_AUTH0_DOMAIN=dev-2cf59a31.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=rrwygXFgF8LgSGhV4ufVQprovN3iITpD
      - REACT_APP_AUTH0_AUDIENCE=https://reservationizr.com
      # - REACT_APP_AUTH0_REDIRECT_URI=https://warricksmith.com/reservationizr
      - REACT_APP_AUTH0_REDIRECT_URI=https://localhost:3002/reservationizr

  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5002:5000'
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/mongo
  db:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'