name: Deploy Production

on:
  release:
    types: [published]

jobs:
  update-main-branch:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git config user.name "administrator"
          git config user.email "administrator@warricksmith.com"
        
      - name: Push to Remote Repository
        run: |
          git remote add remote-repo ssh://administrator:EllaMay11@<warricksmith.com>/C:/DockerApps/reservationizr
          git push remote-repo main
