name: Deploy on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "you@example.com"

      - name: Push to remote repository
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd C:\DockerApps\reservationizr && git pull"
          git push ssh://${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PORT }}/C:/DockerApps/reservationizr main --force
