name: Deploy Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Windows Server 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }} 
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: C:/DockerApps/reservationizr/

        run: |
          ssh $REMOTE_USER@$REMOTE_HOST "
            git pull
            git reset --hard origin/main
          "
