name: Deploy Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Deploy to Windows Server
      run: |
        # Connect to the Windows Server
        $session = New-PSSession -ComputerName $env:HOST -Port $env:PORT -Credential (New-Object System.Management.Automation.PSCredential($env:USERNAME, (ConvertTo-SecureString $env:PASSWORD -AsPlainText -Force)))

        # Change directory to the location of the local repository
        Invoke-Command -Session $session -ScriptBlock {cd C:\DockerApps\reservationizr}

        # Perform a git pull from the main branch
        Invoke-Command -Session $session -ScriptBlock {git pull origin main}

        # Close the session
        Remove-PSSession -Session $session
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}

