name: Deploy on Release
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: windows-latest  # Use a runner with Plink pre-installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "warrick@baybox.co.nz"

      - name: Deploy to remote server repository
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          plink -i key.pem -t -ssh -batch ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /cygdrive/c/DockerApps/reservationizr && git pull"

      - name: Docker compose up
        # Use SSH agent forwarding for credential access
        env:
          SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
        run: |
          plink -A -i key.pem -t -ssh -batch ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /cygdrive/c/DockerApps/reservationizr && docker-compose up --build -d"
